version: '3'

services:
  application:
    container_name: application
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/symfony/
      - ./var/:/var/www/symfony/var/:delegated

  webserver:
    container_name: webserver
    image: nginx:1.24-alpine
    ports:
      - 8080:80
    volumes:
      - ./public/:/var/www/symfony/public/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
